/****************************************************************************************
PURPOSE:
--------
This script demonstrates common SQL analytical techniques on employee sales data:
- Aggregations (SUM, AVG)
- Window functions (DENSE_RANK, RUNNING TOTAL, LAG)
- Month-over-Month (MoM) analysis
- Department-level performance classification

BUSINESS RULES:
---------------
1. Employees can have multiple sales records (one per month).
2. Total sales for an employee = sum of all their monthly sales.
3. Employees are ranked within their department by total sales (highest first).
4. Running totals are calculated per department based on aggregated sales.
5. Month-over-Month comparison uses total company sales per month.
6. Only departments with total sales >= 100,000 are evaluated for performance.
7. Employees are classified as:
   - Top Performer: employee total sales > department average sales
   - Below Average: otherwise

HOW THE SCRIPT WORKS:
---------------------
Step 1: Create the Employees_Info table.
Step 2: Insert sample employee and monthly sales data.
Step 3: Calculate total and average monthly sales per employee.
Step 4: Rank employees within each department by total sales.
Step 5: Calculate running total of sales per department.
Step 6: Perform Month-over-Month sales comparison.
Step 7: Filter high-performing departments and classify employees.
****************************************************************************************/


/****************************************************************************************
TABLE: Employees_Info
---------------------
This table stores employee master data along with monthly sales information.

Column Descriptions:
- EmployeeID     : Unique identifier for each employee
- EmployeeName   : Name of the employee
- Department     : Department where the employee works
- ManagerID      : ID of the employee's manager
- HireDate       : Date the employee was hired
- MonthlySalary  : Employee's fixed monthly salary
- SalesAmount    : Sales generated by the employee in a given month
- Month          : Month for which the sales record applies
****************************************************************************************/

CREATE TABLE Employees_Info (
    EmployeeID INT,
    EmployeeName VARCHAR(50),
    Department VARCHAR(50),
    ManagerID INT,
    HireDate DATE,
    MonthlySalary INT,
    SalesAmount INT,
    Month DATE
);


/****************************************************************************************
SAMPLE DATA:
------------
Each employee can have multiple rows (one per month).
Sales data is intentionally uneven to demonstrate rankings and comparisons.
****************************************************************************************/

INSERT INTO Employees_Info
(EmployeeID, EmployeeName, Department, ManagerID, HireDate, MonthlySalary, SalesAmount, Month)
VALUES
-- Sales Department
(1, 'Alice', 'Sales', 101, '2020-01-01', 90000, 150000, '2025-01-01'),
(1, 'Alice', 'Sales', 101, '2020-01-01', 90000, 200000, '2025-02-01'),

(2, 'Bob', 'Sales', 101, '2021-03-15', 85000, 100000, '2025-01-01'),
(2, 'Bob', 'Sales', 101, '2021-03-15', 85000, 120000, '2025-02-01'),

-- HR Department
(3, 'Carol', 'HR', 102, '2019-07-10', 95000, 95000, '2025-01-01'),
(4, 'David', 'HR', 102, '2020-06-25', 87000, 0, '2025-02-01'),

-- IT Department
(5, 'Evan', 'IT', 103, '2022-05-05', 80000, 60000, '2025-01-01'),
(5, 'Evan', 'IT', 103, '2022-05-05', 80000, 75000, '2025-02-01');


/****************************************************************************************
1. TOTAL SALES AND AVERAGE MONTHLY SALES PER EMPLOYEE
****************************************************************************************/

SELECT
    EmployeeID,
    EmployeeName,
    SUM(SalesAmount) AS Total_Sales,
    AVG(SalesAmount) AS Average_Monthly_Sales
FROM Employees_Info
GROUP BY EmployeeID, EmployeeName;


/****************************************************************************************
2. RANK EMPLOYEES WITHIN EACH DEPARTMENT BY TOTAL SALES
****************************************************************************************/

SELECT
    EmployeeID,
    EmployeeName,
    Department,
    SUM(SalesAmount) AS Total_Sales,
    DENSE_RANK() OVER (
        PARTITION BY Department
        ORDER BY SUM(SalesAmount) DESC
    ) AS Department_Rank
FROM Employees_Info
GROUP BY EmployeeID, EmployeeName, Department;


/****************************************************************************************
3. RUNNING TOTAL OF SALES PER DEPARTMENT
****************************************************************************************/

SELECT
    Department,
    MONTH(Month) AS Sales_Month,
    SUM(SalesAmount) AS Monthly_Sales,
    SUM(SUM(SalesAmount)) OVER (
        PARTITION BY Department
        ORDER BY MONTH(Month)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS Running_Total
FROM Employees_Info
GROUP BY Department, MONTH(Month);


/****************************************************************************************
4. MONTH-OVER-MONTH (MoM) SALES COMPARISON
****************************************************************************************/

WITH Monthly_Sales AS (
    SELECT
        YEAR(Month) AS Sales_Year,
        MONTH(Month) AS Sales_Month,
        DATENAME(MONTH, Month) AS Month_Name,
        SUM(SalesAmount) AS Total_Sales
    FROM Employees_Info
    GROUP BY YEAR(Month), MONTH(Month), DATENAME(MONTH, Month)
)
SELECT
    *,
    LAG(Total_Sales) OVER (ORDER BY Sales_Year, Sales_Month) AS Previous_Month_Sales,
    Total_Sales - LAG(Total_Sales) OVER (ORDER BY Sales_Year, Sales_Month) AS MoM_Difference
FROM Monthly_Sales;


/****************************************************************************************
5. DEPARTMENT FILTERING AND EMPLOYEE PERFORMANCE CLASSIFICATION
****************************************************************************************/

WITH Department_Sales AS (
    SELECT
        Department,
        SUM(SalesAmount) AS Department_Total_Sales,
        AVG(SalesAmount) AS Department_Average_Sales
    FROM Employees_Info
    GROUP BY Department
    HAVING SUM(SalesAmount) >= 100000
),
Employee_Sales AS (
    SELECT
        EmployeeID,
        EmployeeName,
        Department,
        SUM(SalesAmount) AS Employee_Total_Sales
    FROM Employees_Info
    GROUP BY EmployeeID, EmployeeName, Department
)
SELECT
    e.EmployeeID,
    e.EmployeeName,
    e.Department,
    e.Employee_Total_Sales,
    d.Department_Total_Sales,
    d.Department_Average_Sales,
    CASE
        WHEN e.Employee_Total_Sales > d.Department_Average_Sales
            THEN 'Top Performer'
        ELSE 'Below Average'
    END AS Performance_Status
FROM Employee_Sales e
JOIN Department_Sales d
    ON e.Department = d.Department;