/*
==========================================================================================
Purpose:
------------------------------------------------------------------------------------------
This SQL script calculates the total sales revenue generated by each salesperson.
- For each salesperson, it sums the prices of all sales made by their customers.
- If a salesperson has no customers, the total revenue is reported as 0.
- If a customer has no sales, their contribution is considered 0.

Business Rules Implemented:
1. Null totals (from no sales) are replaced with 0.

How the Query Works (Step-by-Step):
1. Tables for Salesperson, Customer, and Sales are created and populated with sample data.
2. Method 1 uses a CTE to sum sales per salesperson and then joins it with the Salesperson table.
3. Method 2 directly left joins Salesperson ? Customer ? Sales, aggregates, and handles nulls.
==========================================================================================
*/

-- Drop tables if they already exist to avoid errors when re-running the script
IF OBJECT_ID('Sales', 'U') IS NOT NULL DROP TABLE Sales;
IF OBJECT_ID('Customer', 'U') IS NOT NULL DROP TABLE Customer;
IF OBJECT_ID('Salesperson', 'U') IS NOT NULL DROP TABLE Salesperson;


------------------------------------------------------------------------------------------
-- Create Salesperson table
------------------------------------------------------------------------------------------
CREATE TABLE Salesperson (
    salesperson_id INT PRIMARY KEY, -- Unique ID for each salesperson
    name NVARCHAR(50)               -- Name of the salesperson
);

-- Sample data for Salesperson
INSERT INTO Salesperson (salesperson_id, name) VALUES
(1, 'Alice'),
(2, 'Bob'),
(3, 'Jerry'); -- Note: Jerry has no customers to test the 0 total scenario


------------------------------------------------------------------------------------------
-- Create Customer table
------------------------------------------------------------------------------------------
CREATE TABLE Customer (
    customer_id INT PRIMARY KEY,         -- Unique ID for each customer
    salesperson_id INT,                  -- ID of the salesperson responsible for the customer
    FOREIGN KEY (salesperson_id) REFERENCES Salesperson(salesperson_id)
);

-- Sample data for Customer
INSERT INTO Customer (customer_id, salesperson_id) VALUES
(1, 1), -- Customer 1 is assigned to Alice
(2, 1), -- Customer 2 is assigned to Alice
(3, 2); -- Customer 3 is assigned to Bob


------------------------------------------------------------------------------------------
-- Create Sales table
------------------------------------------------------------------------------------------
CREATE TABLE Sales (
    sale_id INT PRIMARY KEY,     -- Unique ID for each sale
    customer_id INT,             -- ID of the customer who made the purchase
    price INT,                   -- Price paid by the customer
    FOREIGN KEY (customer_id) REFERENCES Customer(customer_id)
);

-- Sample data for Sales
INSERT INTO Sales (sale_id, customer_id, price) VALUES
(1, 2, 892),  -- Customer 2 paid 892
(2, 1, 354),  -- Customer 1 paid 354
(3, 3, 988),  -- Customer 3 paid 988
(4, 3, 856);  -- Customer 3 paid another 856


------------------------------------------------------------------------------------------
-- Check inserted data (optional, for beginners)
------------------------------------------------------------------------------------------
SELECT * FROM Salesperson;
SELECT * FROM Customer;
SELECT * FROM Sales;


------------------------------------------------------------------------------------------
-- Method 1: Using a CTE
------------------------------------------------------------------------------------------
WITH cte1 AS (
    SELECT
        c.salesperson_id,
        SUM(s.price) AS price -- Sum of all sales for each salesperson
    FROM Customer c
    LEFT JOIN Sales s
        ON c.customer_id = s.customer_id
    GROUP BY c.salesperson_id
)
SELECT
    s.salesperson_id,
    s.name,
    ISNULL(t.price, 0) AS total -- Convert NULL to 0 for salespersons with no customers
FROM Salesperson s
LEFT JOIN cte1 t
    ON t.salesperson_id = s.salesperson_id;


------------------------------------------------------------------------------------------
-- Method 2: Single query with left joins (simpler approach)
------------------------------------------------------------------------------------------
SELECT
    sa.salesperson_id,
    sa.name,
    ISNULL(SUM(s.price), 0) AS total -- Sum sales and handle nulls for no customers/sales
FROM Salesperson sa
LEFT JOIN Customer c
    ON sa.salesperson_id = c.salesperson_id
LEFT JOIN Sales s
    ON s.customer_id = c.customer_id
GROUP BY sa.salesperson_id, sa.name;
